# Base compose file. Used for local development.
version: '2'
services:
  # Web server
  webserver:
    extends:
      file: docker/docker-compose-common.yml
      service: apache
    container_name: webserver
    depends_on:
      - mysql
      - php-fpm
      - redis
    links:
      - mysql
      - php-fpm
      - redis
    volumes:
      - .:/var/www/html
    env_file:
      - docker/env/environment.yml
      - docker/env/environment.development.yml
    environment:
      - VIRTUAL_HOST=.app.webserver.docker
      - VIRTUAL_PORT=80
  # PHP server
  php-fpm:
    extends:
      file: docker/docker-compose-common.yml
      service: php-fpm
    container_name: php_fpm
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    expose:
      - "9000"
      - "9001"
    volumes:
      - .:/var/www/html
    env_file:
      - docker/env/environment.yml
      - docker/env/environment.development.yml
    environment:
      - POSTFIX_RELAYHOST=[mail]:1025
  # Database
  mysql:
    extends:
      file: docker/docker-compose-common.yml
      service: mysql
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/data/sql:/docker-entrypoint-initdb.d
    env_file:
      - docker/env/environment.yml
      - docker/env/environment.development.yml
  # Cache
  redis:
    extends:
      file: docker/docker-compose-common.yml
      service: redis
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
  # Composer
  composer:
    build: docker/applications/composer
    container_name: composer
    volumes_from: 
      - php-fpm
    volumes:
      - composer:/composer
    working_dir: /var/www/html
    environment:
      - COMPOSER_PROCESS_TIMEOUT=3600
  # Bower
  bower:
    build: docker/applications/bower
    container_name: bower
    volumes_from: 
      - php-fpm
    volumes:
      - bower:/bower
    working_dir: /var/www/html
  # Mailhog
  mail:
    build: docker/applications/mailhog
    container_name: mail
    volumes:
      - mail:/maildir
    expose:
      - "8025"
    environment:
      - VIRTUAL_HOST=app.mail.docker
      - VIRTUAL_PORT=8025
  # phpMyAdmin
  phpmyadmin:
    build: docker/applications/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=app.phpmyadmin.docker
      - VIRTUAL_PORT=80
    volumes:
      - /sessions
      
# Storage shared volume
volumes:
  mysql:
    driver: local
  redis:
    driver: local
  elk:
    driver: local
  bower:
    driver: local
  composer:
    driver: local
  mail:
    driver: local
